- name: "create directory on node server"
  hosts: "node"
  become: "false"

  tasks:
    - name: create demo directory in /tmp
      ansible.builtin.file:
        path: /tmp/ansible-demo-dir
        state: directory


