- name: install nginx using condition
  hosts: node
  become: yes

  vars_files:
    - web_vars.yaml
    
  tasks:
    - name : print os family
      ansible.builtin.debug:
        msg: "this servere os family is {{ansible_os_family}}"
    
    - name: install nginx only on redhat family
      ansible.builtin.package:
         name: "{{web_package}}"
         state: present
      when: ansible_os_family == "Redhat"   

    - name : start naginx only on redhat family
      ansible.builtin.service:
          name: "{{web_service}}"
          state: started
          enabled: yes     
      when: ansible_os_family == "Redhat"    
    
    - name: This task should skip on redhar family
      ansible.builtin.debug:
        msg: "This is Debian server"
      when: ansible_os_family == "Debian"