# - name: delete asw security group
#   hosts: localhost
#   connection: local

#   vars:
#     aws_region: us-east-1
#     vpc_id: vpc-093d1d6550b8b6b9b
#     security_group_name: ansible-practice-sg

#   tasks:
#     - name: delete security group
#       amazon.aws.ec2_security_group:
#          name: "{{security_group_name}}"
#          vpc_id: "{{vpc_id}}"
#          region: "{{aws_region}}"
#          state: absent
#       register: delete_sg_result


#     - name: print delete result
#       ansible.builtin.debug:
#           msg: "security group {{security_group_name}}"

# ---
# - name: Delete multiple AWS security groups
#   hosts: localhost
#   connection: local
#   gather_facts: false

#   vars:
#     aws_region: us-east-1
#     vpc_id: vpc-093d1d6550b8b6b9b

#     security_groups:
#       - mongodb-security-1
#       - nginx-security-1
#       - app-security-1

#   tasks:
#     - name: Delete security groups
#       amazon.aws.ec2_security_group:
#         name: "{{ item }}"
#         vpc_id: "{{ vpc_id }}"
#         region: "{{ aws_region }}"
#         state: absent
#       loop: "{{ security_groups }}"
#       register: delete_sg_results

#     - name: Print delete result
#       ansible.builtin.debug:
#         msg: "Delete task completed for security group {{ item.item }}"
#       loop: "{{ delete_sg_results.results }}"

---
- name: Delete EC2 instances
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Terminate EC2 instances by name
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        region: "{{ aws_region }}"
        state: absent
      loop: "{{ instance_names }}"