- name: multiple packages using loop
  hosts: node
  become: yes

  tasks:
    - name: install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        -git
        -vim
        -wget  