- name: install ngnix using Variables
  hosts: node
  become: yes

  vars_files:
    - web_vars.yml

  tasks:
    - name: install web package
      ansible.builtin.package:
        name: "{{web_package}}"
        state: present

    - name: start and enable web package
      ansible.builtin.service:
        name: "{{web_service}}"
        state: started
        enable: yes   