- name: "install and start nginx"
  hosts: "localhost"
  become: yes
  
  vars:
   web_package: nginx
   web_service: nginx

  tasks:
    - name: "install web web_package"
      ansible.builtin.package:
       name: "{{web_package}}"
       state: present

    - name: "start and enable web web_service"
      ansible.builtin.service:
       name: "{{web_service}}"
       state: started
       enabled: yes

      